#%RAML 1.0 Trait

description:  Requires client-id and client-secret headers for the request.
headers:
  client-id: 
    description: The ID of the client making the request.
    type: string
  client-secret: 
    description: The secret key of the client.
    type: string